# **Preparation**

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.10.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from cycler>=0.10->matplotlib>=1.5.1->mlxtend) (1.15.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2018.9)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.0.1)

In [ ]:
import pandas as pd
import numpy as np
import random

# **Import&Clean Data**

In [ ]:
df = pd.read_csv('/content/Prod_Rec.csv')
df

           Timestamp  โปรแกรมแท้  ...  กระบองเพชรพูดได้  ROV Skin
0   10/28/2021 14:05         NaN  ...                 0         0
1   10/28/2021 14:06         NaN  ...                 0         1
2   10/28/2021 14:06         NaN  ...                 0         0
3   10/28/2021 14:06         NaN  ...                 0         0
4   10/28/2021 14:06         NaN  ...                 0         0
5   10/28/2021 14:06         NaN  ...                 0         1
6   10/28/2021 14:06         NaN  ...                 0         0
7   10/28/2021 14:06         NaN  ...                 0         1
8   10/28/2021 14:06         NaN  ...                 0         0
9   10/28/2021 14:06         0.0  ...                 0         0
10  10/28/2021 14:06         0.0  ...                 0         0
11  10/28/2021 14:07         1.0  ...                 0         0
12  10/28/2021 14:07         1.0  ...                 0         0
13  10/28/2021 14:07         NaN  ...                 0         0
14  10/28/2021 14:07         NaN  ...                 0         0
15  10/28/2021 14:07         NaN  ...                 0         1
16  10/28/2021 14:07         1.0  ...                 0         0
17  10/28/2021 14:07         1.0  ...                 0         0
18  10/28/2021 14:07         1.0  ...                 0         0
19  10/28/2021 14:07         0.0  ...                 0         0
20  10/28/2021 14:07         1.0  ...                 1         1
21  10/28/2021 14:07         NaN  ...                 0         0
22  10/28/2021 14:07         0.0  ...                 0         0
23  10/28/2021 14:07         NaN  ...                 0         0
24  10/28/2021 14:08         1.0  ...                 0         0
25  10/28/2021 14:08         1.0  ...                 0         0
26  10/28/2021 14:08         1.0  ...                 0         1
27  10/28/2021 14:08         1.0  ...                 0         1
28  10/28/2021 14:09         1.0  ...                 0         0

[29 rows x 28 columns]

In [ ]:
df = df.drop(['โปรแกรมแท้','เครื่องซักผ้า','NONE'],1)

In [ ]:
df = df.drop('Timestamp',1)

In [ ]:
def reto(x):
  if x == 5:
    x = np.random.randint(0,2)
  return int(x)
df = df.fillna(5)
df = df.applymap(reto)

In [ ]:
df = df.drop(['เคส ipad'],1)

In [ ]:
df

    รองเท้าวิ่ง  ผักกรอบ  ...  กระบองเพชรพูดได้  ROV Skin
0             1        1  ...                 0         0
1             1        0  ...                 0         1
2             1        0  ...                 0         0
3             1        0  ...                 0         0
4             1        1  ...                 0         0
5             1        0  ...                 0         1
6             1        1  ...                 0         0
7             1        0  ...                 0         1
8             1        1  ...                 0         0
9             1        0  ...                 0         0
10            1        0  ...                 0         0
11            1        1  ...                 0         0
12            1        1  ...                 0         0
13            1        0  ...                 0         0
14            1        0  ...                 0         0
15            1        1  ...                 0         1
16            1        0  ...                 0         0
17            1        0  ...                 0         0
18            0        0  ...                 0         0
19            1        1  ...                 0         0
20            1        0  ...                 1         1
21            1        0  ...                 0         0
22            1        0  ...                 0         0
23            1        0  ...                 0         0
24            1        0  ...                 0         0
25            1        1  ...                 0         0
26            1        0  ...                 0         1
27            1        0  ...                 0         1
28            1        1  ...                 0         0

[29 rows x 23 columns]

# **Product Recommendation**

In [ ]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head(10)

                                antecedents  ... conviction
0  (หูฟัง bluetooth (airpods,truewireless))  ...        inf
1                             (รองเท้าวิ่ง)  ...   1.126437
2                                   (Ebook)  ...        inf
3                             (รองเท้าวิ่ง)  ...   1.072797
4                         (คอร์สเรียนเสริม)  ...   1.100313
5                             (เบาะรองนั่ง)  ...        inf
6                                   (Ebook)  ...   1.310345
7                         (คอร์สเรียนเสริม)  ...   1.034483
8                            (เครื่องดนตรี)  ...   1.103448
9                         (คอร์สเรียนเสริม)  ...   1.008621

[10 rows x 9 columns]

In [ ]:
rules[ (rules['lift'] >= 1.0) &
       (rules['confidence'] >= 0.7) ]

                                          antecedents  ... conviction
0            (หูฟัง bluetooth (airpods,truewireless))  ...        inf
1                                       (รองเท้าวิ่ง)  ...   1.126437
2                                             (Ebook)  ...        inf
5                                       (เบาะรองนั่ง)  ...        inf
6                                             (Ebook)  ...   1.310345
8                                      (เครื่องดนตรี)  ...   1.103448
10  (คอร์สเรียนเสริม, หูฟัง bluetooth (airpods,tru...  ...        inf
11                     (คอร์สเรียนเสริม, รองเท้าวิ่ง)  ...   1.045977
12           (หูฟัง bluetooth (airpods,truewireless))  ...   1.137931
13                                      (รองเท้าวิ่ง)  ...   1.086207
15                         (เบาะรองนั่ง, รองเท้าวิ่ง)  ...        inf
17                                      (เบาะรองนั่ง)  ...   1.655172
18                           (Ebook, คอร์สเรียนเสริม)  ...        inf
19                               (Ebook, รองเท้าวิ่ง)  ...   1.310345
21                                            (Ebook)  ...   1.965517

[15 rows x 9 columns]

# **Conclusion**

>> หูฟัง Bluetooth & รองเท้าวิ่ง - ไปวิ่งก็ต้องมีอะไรฟัง จะทำให้วิ่งได้นานขึ้นไม่น่าเบื่อ

>> เบาะรองนั่ง & คอร์สเรียนเสริม - ซื้อไว้สำหรับนั่งเรียนเสริม ทำให้นั่งสบายขึ้น?